In [40]:
import pandas as pd

In [41]:
# reads csv files in data frames
DataSet1=pd.read_csv("FirstSetQueryResults.csv")
DataSet2=pd.read_csv("SecondSetQueryResults.csv")
DataSet3=pd.read_csv("ThirdSetQueryResults.csv")
DataSet4=pd.read_csv("FourthSetQueryResults.csv")

In [42]:
# removes html tags
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\priya pandey\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\priya pandey\anaconda3\lib\site-packages (from beautifulsoup4) (2.2.1)

In [43]:
from bs4 import BeautifulSoup

In [44]:
# function to remove html tags
def removetags(raw_data):
    cleandata=BeautifulSoup(raw_data, "lxml").text
    return cleandata

In [45]:
# data frame before removing html tags
DataSet1.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,927358,1,927386.0,NaN,2009-05-29 18:09:14,NaN,23303,10030841,<p>I accidentally <strong>committed the wrong ...,89904.0,...,2021-06-30 05:07:30,2021-10-05 13:26:47,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,9,7309.0,NaN,2013-03-16 10:08:31,CC BY-SA 4.0
1,2003505,1,2003515.0,NaN,2010-01-05 01:12:15,NaN,18475,9258686,<p>I want to delete a branch both locally and ...,95592.0,...,2021-10-06 22:38:35,2021-10-06 22:38:35,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5718.0,NaN,NaN,CC BY-SA 4.0
2,5767325,1,5767357.0,NaN,2011-04-23 22:17:18,NaN,9899,8897394,<p>I have an array of numbers and I'm using th...,364969.0,...,2020-05-21 04:20:03,2021-09-24 08:51:22,How can I remove a specific item from an array?,<javascript><arrays>,112,4,1501.0,NaN,NaN,CC BY-SA 4.0
3,16956810,1,16957078.0,NaN,2013-06-06 08:06:45,NaN,6286,8203000,<p>I'm trying to find a way to scan my entire ...,954986.0,...,2017-05-21 11:40:16,2021-08-30 13:56:02,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3029.0,NaN,NaN,CC BY-SA 3.0
4,2906582,1,2906586.0,NaN,2010-05-25 16:39:47,NaN,2298,7782563,<p>I would like to create an HTML button that ...,48523.0,...,2021-04-21 16:46:06,2021-09-22 19:42:43,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN,CC BY-SA 4.0

In [46]:
# removing html tags from body column
DataSet1["Body"]=DataSet1["Body"].apply(removetags)
DataSet1.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,927358,1,927386.0,NaN,2009-05-29 18:09:14,NaN,23303,10030841,I accidentally committed the wrong files to Gi...,89904.0,...,2021-06-30 05:07:30,2021-10-05 13:26:47,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,9,7309.0,NaN,2013-03-16 10:08:31,CC BY-SA 4.0
1,2003505,1,2003515.0,NaN,2010-01-05 01:12:15,NaN,18475,9258686,I want to delete a branch both locally and rem...,95592.0,...,2021-10-06 22:38:35,2021-10-06 22:38:35,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5718.0,NaN,NaN,CC BY-SA 4.0
2,5767325,1,5767357.0,NaN,2011-04-23 22:17:18,NaN,9899,8897394,I have an array of numbers and I'm using the ....,364969.0,...,2020-05-21 04:20:03,2021-09-24 08:51:22,How can I remove a specific item from an array?,<javascript><arrays>,112,4,1501.0,NaN,NaN,CC BY-SA 4.0
3,16956810,1,16957078.0,NaN,2013-06-06 08:06:45,NaN,6286,8203000,I'm trying to find a way to scan my entire Lin...,954986.0,...,2017-05-21 11:40:16,2021-08-30 13:56:02,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3029.0,NaN,NaN,CC BY-SA 3.0
4,2906582,1,2906586.0,NaN,2010-05-25 16:39:47,NaN,2298,7782563,I would like to create an HTML button that act...,48523.0,...,2021-04-21 16:46:06,2021-09-22 19:42:43,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN,CC BY-SA 4.0

In [47]:
DataSet2["Body"]=DataSet2["Body"].apply(removetags)
DataSet2.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,47772157,1,47793764.0,NaN,2017-12-12 12:01:59,NaN,50,127400,I'm on a windows machine without admin right a...,2344958.0,...,2020-02-25 03:26:17,2021-10-08 13:46:46,How to change the default browser used by jupy...,<windows><google-chrome><anaconda><jupyter>,23,0,24.0,NaN,NaN,CC BY-SA 4.0
1,37306672,1,NaN,NaN,2016-05-18 17:39:46,NaN,97,127397,Just installed Visual Studio Code 1.1.1 on a W...,1864541.0,...,2018-07-24 13:36:38,2021-08-17 09:51:40,"Visual Studio Code ""Open With Code"" does not a...",<windows-7><visual-studio-code><windows-7-x64>,21,1,13.0,NaN,NaN,CC BY-SA 3.0
2,22700728,1,41141129.0,NaN,2014-03-27 22:39:46,NaN,78,127395,i ran in a problem using composer for installi...,1315408.0,...,2019-09-24 17:27:51,2021-01-15 08:53:03,Composer loading from cache,<php><composer-php>,9,2,11.0,NaN,NaN,CC BY-SA 3.0
3,70272,1,70296.0,NaN,2008-09-16 08:10:53,NaN,77,127392,"I have an application with one form in it, and...",1500.0,...,2013-11-03 16:14:38,2019-06-21 06:49:01,Single Form Hide on Startup,<c#><vb.net><winforms>,23,0,29.0,NaN,NaN,CC BY-SA 3.0
4,2643462,1,2643598.0,NaN,2010-04-15 07:39:40,NaN,23,127391,I'm trying to access a Active Directory from m...,286295.0,...,NaN,2017-07-27 15:12:33,Setting up SSL on a local xampp/apache server,<php><apache><ssl><https><xampp>,6,1,8.0,NaN,NaN,CC BY-SA 2.5

In [49]:
DataSet3["Body"]=DataSet3["Body"].apply(removetags)
DataSet3.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,26486696,1,26486817.0,NaN,2014-10-21 12:25:42,NaN,22,52801,I have following text input filled by model va...,535556.0,...,NaN,2017-08-11 13:35:37,AngularJS get formatted date in ng-model,<javascript><angularjs><date>,3,0,1.0,NaN,NaN,CC BY-SA 3.0
1,49422588,1,NaN,NaN,2018-03-22 07:12:04,NaN,78,52801,AADSTS70005: response_type 'id_token' is not e...,8913221.0,...,2018-03-22 08:10:32,2021-06-02 13:54:12,AADSTS70005: response_type 'id_token' is not e...,<azure><azure-active-directory>,7,7,5.0,NaN,NaN,CC BY-SA 3.0
2,25275202,1,25275336.0,NaN,2014-08-12 22:35:02,NaN,1,52801,I have a column in a table with a varchar data...,1408809.0,...,2014-08-13 05:10:53,2014-08-13 05:10:53,Converting varchar to numeric type in SQL Server,<sql><sql-server><sql-server-2008-r2><sql-serv...,2,0,1.0,NaN,NaN,CC BY-SA 3.0
3,1143841,1,1143994.0,NaN,2009-07-17 15:03:52,NaN,36,52801,I need a way to count the number of pages of a...,115.0,...,NaN,2013-10-24 11:20:49,Count the number of pages in a PDF in only PHP,<php><pdf>,11,1,10.0,2013-06-17 01:55:52,NaN,CC BY-SA 2.5
4,2940671,1,2940700.0,NaN,2010-05-30 23:04:12,NaN,66,52801,How does one use the x264 C API to encode RBG ...,434051.0,...,2012-04-27 01:38:27,2019-08-20 09:02:45,How does one encode a series of images into H2...,<c><image><h.264><x264>,3,0,62.0,NaN,NaN,CC BY-SA 3.0

In [50]:
DataSet4["Body"]=DataSet4["Body"].apply(removetags)
DataSet4.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,56507839,1,67888605.0,NaN,2019-06-08 15:44:30,NaN,114,53204,Here's my SwiftUI code:\nstruct ContentView : ...,6583.0,...,2019-12-02 14:50:17,2021-10-08 21:04:39,SwiftUI: How to make TextField become first re...,<swift><textfield><swiftui><first-responder>,20,1,52.0,NaN,NaN,CC BY-SA 4.0
1,974680,1,1417817.0,NaN,2009-06-10 10:02:40,NaN,13,53204,I would like to create a photo/video capture a...,22996.0,...,2014-03-12 13:15:59,2018-01-08 09:58:13,onKeyDown() issue,<android><android-view><onkeydown>,8,3,3.0,NaN,NaN,CC BY-SA 3.0
2,3630704,1,3631386.0,NaN,2010-09-02 19:54:48,NaN,7,53204,Does VBA support using an array of range varia...,438322.0,...,NaN,2010-09-03 14:26:26,Using an Array of Ranges in VBA - Excel,<arrays><excel><vba><range>,3,3,NaN,NaN,NaN,CC BY-SA 2.5
3,31675192,1,31693357.0,NaN,2015-07-28 11:37:08,NaN,12,53204,I am using Sonar to generate code review repor...,546888.0,...,NaN,2020-03-28 20:22:15,Not able to start Sonar Server,<sonarqube-4.5>,6,0,3.0,NaN,NaN,CC BY-SA 3.0
4,31305809,1,NaN,NaN,2015-07-08 23:51:42,NaN,4,53203,So I have lot of data currently in excel sprea...,5054433.0,...,2015-07-09 22:53:26,2020-10-01 16:10:18,Using data from an excel sheet to graph in python,<python><excel><matplotlib><graph><xlrd>,1,1,3.0,NaN,NaN,CC BY-SA 3.0

In [51]:
import re
import string

In [52]:
# function to remove punctuation
def removepuctuations(data):
    pattern = r'[' + string.punctuation + ']'
    return re.sub(pattern, '', data)

In [53]:
# removing punctuations from body column
DataSet1["Body"]=DataSet1["Body"].apply(removepuctuations)
DataSet2["Body"]=DataSet2["Body"].apply(removepuctuations)
DataSet3["Body"]=DataSet3["Body"].apply(removepuctuations)
DataSet4["Body"]=DataSet4["Body"].apply(removepuctuations)

In [54]:
# removing punctuations from title column
DataSet1["Title"]=DataSet1["Title"].apply(removepuctuations)
DataSet2["Title"]=DataSet2["Title"].apply(removepuctuations)
DataSet3["Title"]=DataSet3["Title"].apply(removepuctuations)
DataSet4["Title"]=DataSet4["Title"].apply(removepuctuations)

In [55]:
DataSet1 = DataSet1.replace(r'\n',' ', regex=True) 
DataSet1 = DataSet1.replace(r'\t',' ', regex=True)
DataSet1 = DataSet1.replace(r'\r',' ', regex=True)
DataSet1 = DataSet1.replace(r'\b',' ', regex=True)
DataSet1 = DataSet1.replace(r'\f',' ', regex=True)

DataSet2 = DataSet2.replace(r'\n',' ', regex=True) 
DataSet2 = DataSet2.replace(r'\t',' ', regex=True)
DataSet2 = DataSet2.replace(r'\r',' ', regex=True)
DataSet2 = DataSet2.replace(r'\b',' ', regex=True)
DataSet2 = DataSet2.replace(r'\f',' ', regex=True)

DataSet3 = DataSet3.replace(r'\n',' ', regex=True) 
DataSet3 = DataSet3.replace(r'\t',' ', regex=True)
DataSet3 = DataSet3.replace(r'\r',' ', regex=True)
DataSet3 = DataSet3.replace(r'\b',' ', regex=True)
DataSet3 = DataSet3.replace(r'\f',' ', regex=True)

DataSet4 = DataSet4.replace(r'\n',' ', regex=True) 
DataSet4 = DataSet4.replace(r'\t',' ', regex=True)
DataSet4 = DataSet4.replace(r'\r',' ', regex=True)
DataSet4 = DataSet4.replace(r'\b',' ', regex=True)
DataSet4 = DataSet4.replace(r'\f',' ', regex=True)

In [56]:
# merged all 4 files using concat
MergedData = pd.concat([DataSet1,DataSet2,DataSet3,DataSet4])

In [57]:
MergedData.shape

(200000, 23)

In [58]:
# exporting processed file in .csv
MergedData.to_csv("preprocessedMergedData.csv")

In [59]:
# exporting processed files in .txt
MergedData.to_csv("preprocessedMergedData.txt")